-- Berth 9 schema. Plain SQL that runs on PostgreSQL and on H2 (PostgreSQL mode) for zero-setup runs.

-- Trading partners and how they reach us
CREATE TABLE partner (
    id            VARCHAR(40)  PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    country       VARCHAR(2)   NOT NULL,
    city          VARCHAR(100),
    role          VARCHAR(20)  NOT NULL,              -- SUPPLIER | CUSTOMER
    channel       VARCHAR(20)  NOT NULL,              -- SFTP | API | FOLDER
    format        VARCHAR(20)  NOT NULL,
    document      VARCHAR(100),
    schema_name   VARCHAR(40)  NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    gstin         VARCHAR(15),
    edi_id        VARCHAR(15),
    locale        VARCHAR(2)   NOT NULL,
    expected_by   VARCHAR(5),                         -- daily file expected by HH:mm (SLA)
    api_key       VARCHAR(64),
    api_secret    VARCHAR(128)
);

-- Versioned mapping specs: a version is never edited, a new one is added
CREATE TABLE mapping_spec (
    partner_id    VARCHAR(40)  NOT NULL REFERENCES partner (id),
    version       INTEGER      NOT NULL,
    spec_json     VARCHAR      NOT NULL,
    note          VARCHAR(500),
    created_by    VARCHAR(60)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (partner_id, version)
);

-- One row per received file. (partner_id, sha256) makes re-sent files idempotent.
CREATE TABLE file_job (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id    VARCHAR(40)  NOT NULL REFERENCES partner (id),
    file_name     VARCHAR(300) NOT NULL,
    sha256        VARCHAR(64)  NOT NULL,
    channel       VARCHAR(20)  NOT NULL,
    format        VARCHAR(20),
    spec_version  INTEGER,
    status        VARCHAR(20)  NOT NULL,              -- PROCESSING | COMPLETED | NEEDS_REVIEW | REJECTED | FAILED
    total         INTEGER      DEFAULT 0 NOT NULL,
    valid         INTEGER      DEFAULT 0 NOT NULL,
    warnings      INTEGER      DEFAULT 0 NOT NULL,
    errors        INTEGER      DEFAULT 0 NOT NULL,
    size_bytes    BIGINT,
    file_issues   VARCHAR,
    context_json  VARCHAR,
    ack_997       VARCHAR,
    message       VARCHAR(1000),
    received_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at  TIMESTAMP WITH TIME ZONE,
    duration_ms   BIGINT,
    CONSTRAINT uq_file_job_content UNIQUE (partner_id, sha256)
);
CREATE INDEX ix_file_job_received ON file_job (received_at);

-- Every record of every file, with its source row, canonical values, lineage and violations.
CREATE TABLE job_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            BIGINT       NOT NULL REFERENCES file_job (id),
    line_no           BIGINT       NOT NULL,
    business_key      VARCHAR(200),
    status            VARCHAR(20)  NOT NULL,          -- VALID | WARNING | ERROR | DELIVERED | DEAD_LETTER | DISMISSED
    source_json       VARCHAR      NOT NULL,
    values_json       VARCHAR,
    lineage_json      VARCHAR,
    violations_json   VARCHAR,
    delivery_attempts INTEGER      DEFAULT 0 NOT NULL,
    next_attempt_at   TIMESTAMP WITH TIME ZONE,
    last_error        VARCHAR(1000),
    delivered_at      TIMESTAMP WITH TIME ZONE,
    updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX ix_job_record_job ON job_record (job_id, status);
CREATE INDEX ix_job_record_outbox ON job_record (status, next_attempt_at);

-- Audit trail of human fixes in the exceptions queue
CREATE TABLE record_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id     BIGINT       NOT NULL REFERENCES job_record (id),
    action        VARCHAR(20)  NOT NULL,              -- EDIT | REPROCESS | DISMISS | REPLAY
    detail        VARCHAR,
    actor         VARCHAR(60)  NOT NULL,
    acted_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Keys already delivered downstream: duplicate detection across files and idempotent delivery
CREATE TABLE delivered_key (
    dataset       VARCHAR(40)  NOT NULL,              -- invoiced-lines | ordered-lines
    business_key  VARCHAR(200) NOT NULL,
    record_id     BIGINT       NOT NULL,
    delivered_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (dataset, business_key)
);

-- Control numbers for outbound EDI envelopes
CREATE TABLE edi_counter (
    name          VARCHAR(40)  PRIMARY KEY,
    counter_value BIGINT       NOT NULL
);
INSERT INTO edi_counter (name, counter_value) VALUES ('ISA', 1000), ('GS', 500);

-- ---------------------------------------------------------------- reference data (the buyer's ERP)

CREATE TABLE purchase_order (
    po_number     VARCHAR(40)  PRIMARY KEY,
    supplier_id   VARCHAR(40)  NOT NULL,
    currency      VARCHAR(3)   NOT NULL,
    po_date       DATE         NOT NULL,
    status        VARCHAR(20)  NOT NULL
);

CREATE TABLE po_line (
    po_number     VARCHAR(40)   NOT NULL REFERENCES purchase_order (po_number),
    sku           VARCHAR(60)   NOT NULL,
    description   VARCHAR(200),
    ordered_qty   NUMERIC(18,3) NOT NULL,
    invoiced_qty  NUMERIC(18,3) DEFAULT 0 NOT NULL,
    unit_price    NUMERIC(18,4) NOT NULL,
    uom           VARCHAR(10),
    PRIMARY KEY (po_number, sku)
);

CREATE TABLE product (
    sku           VARCHAR(60)   PRIMARY KEY,
    description   VARCHAR(200),
    uom           VARCHAR(10),
    list_price    NUMERIC(18,4) NOT NULL,
    currency      VARCHAR(3)    NOT NULL
);

CREATE TABLE ship_to (
    customer_id   VARCHAR(40)  NOT NULL,
    ship_to_code  VARCHAR(20)  NOT NULL,
    name          VARCHAR(100),
    city          VARCHAR(60),
    state         VARCHAR(10),
    PRIMARY KEY (customer_id, ship_to_code)
);

CREATE TABLE fx_rate (
    currency      VARCHAR(3)    PRIMARY KEY,
    usd_rate      NUMERIC(18,8) NOT NULL
);
